name: create static web
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello World"
      - name: Print files
        run: |
          pwd
          uptime
