name: create static web
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        uses: actions/checkout@v3
      - name: Print files
        run: docker build -t docker.io/bhupendra8888:latest .
      - name: list docker image
        run: docker images
